sudo: required

language: ruby
cache: bundler

rvm:
  - 2.6.3

jobs:
  include:
    - stage: test
      name: rubocop
      script: bundle exec rubocop
      if: env(CD_TEST_IGNORE) IS NOT present

    - stage: test
      name: rspec
      script: gem install bundler & bundle exec rspec
      if: env(CD_TEST_IGNORE) IS NOT present
      
    - stage: build
      name: build docker application image
      script: bash scripts/app_image_build.sh $TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_COMMIT
      if: env(CD_BUILD_IGNORE) IS NOT present AND type NOT IN (pull_request) AND env(CD_DOCKER_USERNAME) IS present AND env(CD_DOCKER_PASSWORD) IS present

    - stage: build
      name: build docker nginx-com image
      script: bash scripts/com_image_build.sh $TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_COMMIT
      if: env(CD_BUILD_IGNORE) IS NOT present AND type NOT IN (pull_request) AND env(CD_DOCKER_USERNAME) IS present AND env(CD_DOCKER_PASSWORD) IS present
        
    - stage: build
      name: build docker nginx-kub image
      script: bash scripts/kub_image_build.sh $TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_COMMIT
      if: env(CD_BUILD_IGNORE) IS NOT present AND type NOT IN (pull_request) AND env(CD_DOCKER_USERNAME) IS present AND env(CD_DOCKER_PASSWORD) IS present