version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    entrypoint: [bin/start]
    image: shawnhiggins/test-app
    container_name: test-app
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./db/production:/var/www/app/db/production
      - ./log:/var/www/app/log
      - asset-volume:/var/www/app/public
    depends_on:
      - db
  nginx:
    image: shawnhiggins/nginx
    container_name: nginx
    volumes:
      - ./log:/var/www/app/log
      - asset-volume:/var/www/app/public
    depends_on:
      - web
    ports:
      - 5050:5050
volumes:
  asset-volume: