debug: false

# maximum wait for a response to any API request (secs)
timeout_req: 60

# maximum wait for a meeting to be ended after end_meeting is called (secs)
timeout_ending: 30

# maximum wait until the bot starts (secs)
timeout_bot_start: 60

servers:
  test-install:
    url: 'http://test-install.blindsidenetworks.com/bigbluebutton/api'
    secret: '8cd8ef52e8e101574e400365b55e11a6'
  bbb-other:
    url: 'http://10.80.174.87/bigbluebutton/api'
    secret: 'ac213a41bb9a522955a125c3f1b4a3d4'